spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq-impl-user
    password: Rabbitmq123Password
    virtual-host: vh-rabbitmq
    listener:
      simple:
        acknowledge-mode: manual
        max-concurrency: 2
        concurrency: 2