spring:
  profiles: dev
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbituser
    password: rabbitpass
    virtual-host: vh-rabbitmq
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3